# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Automation doc generation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-doc-on-pr-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Configure Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Enable Debugging
        run: echo "DEBUG=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Debug Git History
        run: git log --oneline -3

      - name: Debug Environment Variables
        run: |
          echo "SPACE_ID: $SPACE_ID"
          echo "CONFLUENCE_API_TOKEN: ${CONFLUENCE_API_TOKEN:0:4}****" # Oculta parte del token por seguridad
          echo "CONFLUENCE_SPACE_KEY: $CONFLUENCE_SPACE_KEY"

      - name: Test Confluence API Access
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          SPACE_ID: "295237"
        run: |
          curl -X GET "https://your-confluence-instance/rest/api/space/$SPACE_ID" \
            -H "Authorization: Bearer $CONFLUENCE_API_TOKEN" \
            -H "Content-Type: application/json"

      - name: Generate last changes diff file and Generate documentation using GPT4 model
        env:
              GH_GPT4_API_KEY: ${{ secrets.GH_GPT4_API_KEY }}
              CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
              CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
              HF_API_TOKEN: ${{ secrets.MY_HF_TOKEN }}
              SPACE_ID: "295237"
        run: |
            python src/scripts/get_diff.py
            ls -la
            cat diff.txt || echo " diff.txt file empty or not found"
            ls -la $GITHUB_WORKSPACE
            cat $GITHUB_WORKSPACE/diff.txt || echo "Archivo diff.txt vacío o no encontrado"
            python src/doctype_diff_validator/doctype_diff_validator.py
            python src/docs_publisher_controller/gen_doc_controller.py
